### ISSUE TITLE
 ! no field, method or inner class called 'use_cli_format'

### ISSUE THREAD

**Issue by A1exanderAlexeyuk** [OdyOSG/CDMConnector#13]
@ablack3 
library(CDMConnector)
library(DatabaseConnector)
#> 
#> 
#>     dbms
library(dplyr, warn.conflicts = F)
resultsDatabaseSchema <- "alex_alexeyuk_results"
cdmDatabaseSchema <- "cdm_531"
cohortDatabaseSchema <- "alex_alexeyuk_results"
connectionDetails <- createConnectionDetails(
                 dbms = "postgresql",
                 server = "testnode.arachnenetwork.com/synpuf_110k",
                 user = Sys.getenv("ohdsi_password"),
                 password = Sys.getenv("ohdsi_password"),
                 port = "5441"
               )
con <- connect(connectionDetails = connectionDetails)
#> Connecting using PostgreSQL driver
cdm <- cdm_from_con(
  con,
  cdm_schema = "cdm_531",
  cdm_tables = tbl_group("default"),
  write_schema = "alex_alexeyuk_results",
  cohort_tables = c('txpath_test_event', 'txpath_test_tar')
)
#> Warning: <DatabaseConnectorJdbcConnection> uses an old dbplyr interface
#> ℹ Please install a newer version of the package or contact the maintainer
#> This warning is displayed once every 8 hours.
#> Error in `purrr::map()`:
#> ℹ In index: 1.
#> Caused by error in `._jobjRef_dollar()`:
#> ! no field, method or inner class called 'use_cli_format'

#> Backtrace:
#>      ▆
#>   1. ├─CDMConnector::cdm_from_con(...)
#>   2. │ └─purrr::map(...)
#>   3. │   └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
#>   4. │     ├─purrr:::with_indexed_errors(...)
#>   5. │     │ └─base::withCallingHandlers(...)
#>   6. │     ├─purrr:::call_with_cleanup(...)
#>   7. │     └─CDMConnector (local) .f(.x[[i]], ...)
#>   8. │       ├─dplyr::tbl(con, dbplyr::in_schema(cdm_schema, .)) %>% ...
#>   9. │       ├─dplyr::tbl(con, dbplyr::in_schema(cdm_schema, .))
#>  10. │       └─dplyr:::tbl.DBIConnection(...)
#>  11. │         ├─dplyr::tbl(...)
#>  12. │         └─dbplyr:::tbl.src_dbi(...)
#>  13. │           └─dbplyr::tbl_sql(c(subclass, "dbi"), src = src, from = from, ...)
#>  14. │             ├─vars %||% dbplyr_query_fields(src$con, from_sql)
#>  15. │             └─dbplyr:::dbplyr_query_fields(src$con, from_sql)
#>  16. │               └─dbplyr:::dbplyr_fallback(con, "db_query_fields", ...)
#>  17. │                 ├─rlang::eval_bare(expr((!!fun)(con, ...)))
#>  18. │                 ├─dplyr::db_query_fields(con, ...)
#>  19. │                 └─dbplyr:::db_query_fields.DBIConnection(con, ...)
#>  20. │                   └─base::tryCatch(...)
#>  21. │                     └─base (local) tryCatchList(expr, classes, parentenv, handlers)
#>  22. │                       └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>  23. │                         └─value[[3L]](cond)
#>  24. │                           └─cli::cli_abort("Can't query fields.", parent = cnd)
#>  25. │                             └─rlang::abort(...)
#>  26. │                               └─rlang:::signal_abort(cnd, .file)
#>  27. │                                 └─base::signalCondition(cnd)
#>  28. │                                   ├─base::conditionMessage(cond)
#>  29. │                                   └─rlang:::conditionMessage.rlang_error(cond)
#>  30. │                                     └─rlang::cnd_message(c)
#>  31. │                                       └─rlang:::cnd_message_format_prefixed(cnd, parent = TRUE, warning = warning)
#>  32. │                                         └─rlang:::cnd_message_format(cnd, ..., alert = alert)
#>  33. │                                           ├─rlang::is_true(cnd$use_cli_format)
#>  34. │                                           ├─cnd$use_cli_format
#>  35. │                                           └─rJava:::`$.Throwable`(cnd, "use_cli_format")
#>  36. │                                             └─rJava:::._jobjRef_dollar(x[["jobj"]], name)
#>  37. │                                               └─base::stop(...)
#>  38. ├─dplyr::rename_all(., tolower)
#>  39. │ └─dplyr::tbl_vars(.tbl)
#>  40. │   ├─dplyr:::new_sel_vars(tbl_vars_dispatch(x), group_vars(x))
#>  41. │   │ └─base::structure(...)
#>  42. │   └─dplyr:::tbl_vars_dispatch(x)
#>  43. └─base::.handleSimpleError(...)
#>  44.   └─purrr (local) h(simpleError(msg, call))
#>  45.     └─cli::cli_abort(...)
#>  46.       └─rlang::abort(...)

**Comment by ablack3** [comment]
Try using the RPostgres driver like this.

``` r
library(CDMConnector)
library(dplyr, warn.conflicts = F)

con <- DBI::dbConnect(RPostgres::Postgres(),
                      dbname   = "synpuf_110k",
                      host     = "testnode.arachnenetwork.com",
                      user     = Sys.getenv("ODYS_DB_USER"),
                      password = Sys.getenv("ODYS_DB_PASSWORD"),
                      port = Sys.getenv("ODYS_DB_PORT"))


cdm <- cdm_from_con(
  con,
  cdm_schema = "cdm_531",
  cdm_tables = tbl_group("default"),
  write_schema = "alex_alexeyuk_results",
  cohort_tables = c('txpath_test_event', 'txpath_test_tar')
)

cdm$txpath_test_event
#> # Source:   table<"alex_alexeyuk_results"."txpath_test_event"> [?? x 4]
#> # Database: postgres  [ohdsi@testnode.arachnenetwork.com:5441/synpuf_110k]
#>    cohort_definition_id subject_id cohort_start_date cohort_end_date
#>                   <int>    <int64> <date>            <date>         
#>  1                 1726        821 2009-08-31        2010-11-14     
#>  2                 1726       1005 2010-12-23        2010-12-23     
#>  3                 1726       1284 2009-08-14        2010-05-22     
#>  4                 1726       1802 2009-05-04        2010-08-07     
#>  5                 1726       2225 2009-08-15        2010-12-24     
#>  6                 1726       2241 2008-04-01        2010-12-31     
#>  7                 1726       2427 2010-04-29        2010-09-17     
#>  8                 1726       2863 2008-08-08        2010-08-09     
#>  9                 1726       3653 2010-07-24        2010-12-28     
#> 10                 1726       3818 2010-10-31        2010-12-26     
#> # … with more rows
cdm$txpath_test_tar
#> # Source:   table<"alex_alexeyuk_results"."txpath_test_tar"> [?? x 4]
#> # Database: postgres  [ohdsi@testnode.arachnenetwork.com:5441/synpuf_110k]
#>    cohort_definition_id subject_id cohort_start_date cohort_end_date
#>                   <int>    <int64> <date>            <date>         
#>  1                  574          2 2008-10-08        2010-11-01     
#>  2                  574          7 2008-08-13        2010-09-07     
#>  3                  574         11 2008-09-17        2010-12-19     
#>  4                  574         12 2009-10-19        2010-11-23     
#>  5                  574         13 2009-09-27        2010-09-22     
#>  6                  574         17 2009-09-15        2010-11-11     
#>  7                  574         19 2008-03-22        2010-04-03     
#>  8                  574         20 2009-05-09        2010-09-13     
#>  9                  574         21 2010-03-28        2010-12-15     
#> 10                  574         25 2008-03-13        2010-12-01     
#> # … with more rows
cdm$person
#> # Source:   table<"cdm_531"."person"> [?? x 18]
#> # Database: postgres  [ohdsi@testnode.arachnenetwork.com:5441/synpuf_110k]
#>    person_id gende…¹ year_…² month…³ day_o…⁴ birth_datetime race_conce…⁵ ethni…⁶
#>        <int>   <int>   <int>   <int>   <int> <dttm>                <int>   <int>
#>  1         1    8507    1923       5       1 NA                     8527  3.80e7
#>  2         2    8507    1943       1       1 NA                     8527  3.80e7
#>  3         3    8532    1936       9       1 NA                     8527  3.80e7
#>  4         4    8507    1941       6       1 NA                        0  3.80e7
#>  5         5    8507    1936       8       1 NA                     8527  3.80e7
#>  6         6    8507    1943      10       1 NA                     8516  3.80e7
#>  7         7    8507    1922       7       1 NA                     8527  3.80e7
#>  8         8    8507    1935       9       1 NA                     8527  3.80e7
#>  9         9    8532    1976       9       1 NA                     8527  3.80e7
#> 10        10    8532    1938      10       1 NA                     8516  3.80e7
#> # … with more rows, 10 more variables: location_id <int>, provider_id <int>,
#> #   care_site_id <int>, person_source_value <chr>, gender_source_value <chr>,
#> #   gender_source_concept_id <int>, race_source_value <chr>,
#> #   race_source_concept_id <int>, ethnicity_source_value <chr>,
#> #   ethnicity_source_concept_id <int>, and abbreviated variable names
#> #   ¹​gender_concept_id, ²​year_of_birth, ³​month_of_birth, ⁴​day_of_birth,
#> #   ⁵​race_concept_id, ⁶​ethnicity_concept_id

DBI::dbDisconnect(con)
```

<sup>Created on 2023-03-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ablack3** [comment]
If it works for you go ahead and close the issue as completed please. If not post a reprex with your error.

**Comment by A1exanderAlexeyuk** [comment]
Thank you, Adam! It works
