### ISSUE TITLE
Error in cdm_from_con function

### ISSUE THREAD

**Issue by ipiper01** [OdyOSG/CDMConnector#19]
I am getting an error when I try to run the cdm_from_con function.

I create a DBI connection using the dbConnect function which runs fine, then when I pass the connection into the cdm_from_con function, I get the following error:

Error in connection_sql_tables(conn@ptr, catalog_name = catalog_name,  : 
  nanodbc/nanodbc.cpp:4483: 00000: [Simba][Hardy] (115) Connection failed with error: SSL_read: Resource temporarily unavailable 

This is the code I am using: 

con <- DBI::dbConnect(drv = odbc::odbc(),
                      driver = "Simba Spark ODBC Driver 64-bit",
                      host = "<>",
                      httppath = "<>",
                      port = 443,
                      uid = "token",
                      pwd = "<>",
                      authmech = 3,
                      schema = "schema-name",
                      sparkservertype = 3,
                      ssl = 1,
                      thrifttransport = 2,
                      usenativequery = 1)

cdm <- cdm_from_con(con, cdm_schema = "schema-name")

It worked the first time I ran the cdm_from_con function but hasn't worked since.

I don't understand the error so any help would be appreciated, thanks.

**Comment by ablack3** [comment]
Unfortunately my Databricks spark test server is offline so I can't test it. I'll test it when it is online. Thanks for reporting!

**Comment by ablack3** [comment]
This looks like an error with your server actually. Can you confirm that you are able to connect to your server using odbc outside of R?

**Comment by ipiper01** [comment]
Thanks for looking into this. Yes I can connect outside of R. 

Also the DBI connection above does work, for example, when querying a database, using the DBI::dbGetQuery function.

**Comment by ablack3** [comment]
Ok that's good news.

Can we confirm you have the correct cdm schema? I usually don't see dashes "-" in schema names.

Maybe try running this.
```
con <- DBI::dbConnect(... your details here...)
DBI::dbGetQuery(con, "select count * as n from schema-name.person")
```

**Comment by ipiper01** [comment]
Yes sorry, I was just using schema-name as a placeholder. If I use for example rwd_cprd_gold_omopv5, then the query runs fine.

**Comment by ipiper01** [comment]
I mean that the dbGetQuery runs fine, but I still have the issue with cdm_from_con

**Comment by ablack3** [comment]
Oh ok. Can you provide a reproducible example? i.e. a reprex https://reprex.tidyverse.org/

**Comment by ipiper01** [comment]
I'm not really sure how to provide further than what I gave in my original post, since it involves credentials. Here's the code again with the schema name:

host <- ""
httppath <- ""
pwd <- ""

con <- DBI::dbConnect(drv = odbc::odbc(),
                      driver = "Simba Spark ODBC Driver 64-bit",
                      host = host,
                      httppath = httppath,
                      port = 443,
                      uid = "token",
                      pwd = pwd,
                      authmech = 3,
                      schema = "rwd-cfor.rwd_cprd_gold_omopv5",
                      sparkservertype = 3,
                      ssl = 1,
                      thrifttransport = 2,
                      usenativequery = 1)
 
cdm <- CDMConnector::cdm_from_con(con, cdm_schema = "rwd_cprd_gold_omopv5")
#> Error in connection_sql_tables(conn@ptr, catalog_name = catalog_name, : nanodbc/nanodbc.cpp:4483: 00000: [Simba][Hardy] (115) Connection failed with error: SSL_read: Resource temporarily unavailable

**Comment by ablack3** [comment]
ok that works. Sorry I don't have an easy answer for you (and I don't currently have a databricks test environment to test on).
You could run traceback() to see the last stack trace. That might help.

Also try
```
con <- con <- DBI::dbConnect(drv = odbc::odbc(),....)
dplyr::tbl(con, dbplyr::in_schema("rwd_cprd_gold_omopv5", "person"))

dplyr::tbl(con, DBI::Id(schema = "rwd_cprd_gold_omopv5", table = "person"))
```
See if those work.

**Comment by ablack3** [comment]
The traceback is very helpful! I think you identified a bug. I have created a fix. Will you please reinstall the package from github using the code below and try again.

`remotes::install_github("OdyOSG/CDMConnector")`

**Comment by ipiper01** [comment]
The cdm_from_con function is working now! Glad you were able to identify the bug. Thanks for your help!
